#!/bin/python3

import argparse
import os
import subprocess
import re
import sys

out_exe = "./test_prog.bin"

def getExpectedExitCode(filePath):
    # Parses the 'Exit code: x' line from the top of the .c file.
    with open(filePath, 'r') as f:
        firstLine = f.readline()
        match = re.search(r'Exit code:\s*(\d+)', firstLine)
        if match:
            return int(match.group(1))
    return None

def executeProgram(expectedReturnCode: int, testPath: str, workDirectory: str, printOutput: bool) -> bool:
    ret = False
    try:
        # Run the simulation.
        cmd = ['vsim',
               '-c',
               '-voptargs=+acc',
               f'-gFILE_PATH={out_exe}',
               'work.cpu_test',
               '-do', './run_fpga.tcl'
            ]

        result = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=workDirectory, text=True, check=True)

        # Extract signal value from output
        match = re.search(r"REGISTER_VALUE_OUTPUT:\s*([0-9a-fA-FzxZX]+)", result.stdout)
        if match:
            reg_value = match.group(1)
        else:
            raise RuntimeError("Failed to capture register value from simulation output.")
        
        if reg_value == expectedReturnCode:
            print(f"[\033[92mPASS\033[0m] {testPath}: Program returned {reg_value} as expected.")
            ret = True
        else:
            print(f"[\033[91mFAIL\033[0m] {testPath}: Expected {expectedReturnCode}, but got {reg_value}.")
    
        if printOutput:
            print(f"Output:\n{result.stderr}")

    finally:
        # Cleanup generated executable.
        if os.path.exists(out_exe):
            os.remove(out_exe)
    return ret

def getInnerTestsFolder(inputDir) -> str|None:
    validDir = os.path.join(inputDir, 'valid')
    return validDir if os.path.exists(validDir) else None

def runTestsFromInputRoute(compilerPath: str, vhdlPath: str, inputFolder: str, verboseLevel: int, optimize: bool):
    if os.path.exists(inputFolder):
        # Running a folder with the valid and invalid folders.
        print(f"--- {inputFolder} ---")
        results = runTests(compilerPath, vhdlPath, inputFolder, verboseLevel, optimize)
    else:
        print(f"Error: Input test folder is invalid")
        sys.exit(1)

    print(f"Summary: {results['passed']} passed, {results['failed']} failed, {results['skipped']} skipped.")
    retCode = (results["failed"] + results['skipped']) > 0

    print("\n-----------------------")
    print("OK" if retCode == 0 else "ERROR")

    sys.exit(retCode)

def runTests(compilerPath: str, vhdlPath: str, folderPath: str, verboseLevel: int, optimize: bool) -> dict[str, int]:
    results = dict(passed = 0, failed = 0, skipped = 0)
    print(f"\n--- Running Valid Tests ---")

    # Create a work project. This creates the folder vhdlPath/work.
    subprocess.run(["vlib", "work"], check=True, cwd=vhdlPath)

    workDirectory = os.path.join(vhdlPath, "work")

    # Run the makefile inside the work directory.
    subprocess.run(["make"], check=True, cwd=workDirectory)

    for testFilePath in sorted(os.listdir(folderPath)):
        if not testFilePath.endswith('.c'):
            continue

        path = os.path.join(folderPath, testFilePath)
        expectedReturnCode = getExpectedExitCode(path)
        
        if expectedReturnCode is None:
            print(f"[\033[93mSKIP\033[0m] {testFilePath}: No 'Exit code: x' header found.")
            results["skipped"] += 1
            continue

        # Compile the binary file.
        cmd = [compilerPath, path, "-o", out_exe, "-m", "calci32"]
        if optimize:
            cmd += ["-O"]
        compileCFile = subprocess.run(cmd, capture_output=True)

        if compileCFile.returncode != 0:
            print(f"[\033[91mFAIL\033[0m] {testFilePath}: Failed to compile valid program.")
            if verboseLevel > 0:
                print(f"Output:\n{compileCFile.stderr.decode()}")
            
            results["failed"] += 1
            continue

        # Execute generated program.
        goodExecution = executeProgram(expectedReturnCode, testFilePath, workDirectory, verboseLevel > 0)
        if goodExecution:
            results["passed"] += 1
        else:
            results["failed"] += 1

    return results

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="fpga-tests")
    parser.add_argument("compiler", 
                        help="Path to the compiler executable")
    parser.add_argument("vhdl", 
                        help="Path to the VHDL project")
    parser.add_argument("tests", 
                        help="Path to the test folder. It can be a folder containing subfolders of tests")
    parser.add_argument("-v", "--verbose",
                        action="count", default=0,
                        help="Print output from the compiler.")
    parser.add_argument("-O", "--optimize",
                        action="store_true",
                        help="Run tests with optimizations.")

    args = parser.parse_args()
    
    if not os.path.exists(args.compiler):
        print(f"Error: Compiler not found at {args.compiler}")
        sys.exit(1)

    runTestsFromInputRoute(args.compiler, args.vhdl, args.tests, args.verbose, args.optimize)