#!/bin/python3

import argparse
import os
import subprocess
import re
import sys

def getExpectedExitCode(filePath):
    # Parses the 'Exit code: x' line from the top of the .c file.
    with open(filePath, 'r') as f:
        firstLine = f.readline()
        match = re.search(r'Exit code:\s*(\d+)', firstLine)
        if match:
            return int(match.group(1))
    return None

def executeProgram(testPath: str, binaryPath: str, vhdlDirectory: str, printOutput: bool) -> bool:
    ret = False
    try:
        # Run the simulation.
        baseFolder = os.path.dirname(os.path.abspath(__file__))
        linkerRoute =  os.path.join(baseFolder, "run_fpga.tcl")
        
        cmd = ['vsim',
               '-c',
               '-voptargs=+acc',
               f'-gFILE_PATH={binaryPath}',
               'work.cpu_test',
               '-do', os.path.abspath(linkerRoute)
            ]

        if printOutput:
            cmdStr = " ".join(cmd)
            print(f"Command:\n{cmdStr}")

        result = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=vhdlDirectory, text=True, check=True)

        # Fetch R0 value.
        match = re.search(r"R0:\s*([0-9a-fA-FzxZX]+)", result.stdout)
        if match:
            r0Val: int = int(match.group(1))
        else:
            raise RuntimeError("Failed to capture register value from simulation output.")

        # Fetch CPUState value.
        match = re.search(r"CPU_STATE:\s*(\w+)", result.stdout)
        if match:
            cpuState: str = match.group(1)
        else:
            raise RuntimeError("Failed to capture register value from simulation output.")

        if r0Val == 0 and cpuState == "CPU_BRK":
            print(f"[\033[92mPASS\033[0m] {testPath}: Program returned {r0Val} as expected.")
            ret = True
        else:
            print(f"[\033[91mFAIL\033[0m] {testPath}. R0 = {r0Val}. CPU state = {cpuState}")
    
    finally:
        # Cleanup generated binary.
        if os.path.exists(binaryPath):
            os.remove(binaryPath)
    return ret

def getInnerTestsFolder(inputDir) -> str|None:
    validDir = os.path.join(inputDir, 'valid')
    return validDir if os.path.exists(validDir) else None

def runTestsFromInputRoute(compilerPath: str, vhdlPath: str, inputFolder: str, verboseLevel: int, optimize: bool):
    if os.path.exists(inputFolder):
        # Running a folder with the valid and invalid folders.
        print(f"--- {inputFolder} ---")
        results = runTests(compilerPath, vhdlPath, inputFolder, verboseLevel, optimize)
    else:
        print(f"Error: Input test folder is invalid")
        sys.exit(1)

    print(f"Summary: {results['passed']} passed, {results['failed']} failed, {results['skipped']} skipped.")
    retCode = (results["failed"] + results['skipped']) > 0

    print("\n-----------------------")
    print("OK" if retCode == 0 else "ERROR")

    sys.exit(retCode)

def runTests(compilerPath: str, vhdlPath: str, folderPath: str, verboseLevel: int, optimize: bool) -> dict[str, int]:
    print(f"\n--- Running Valid Tests ---")
    results: dict[str, int] = dict(passed = 0, failed = 0, skipped = 0)

    # Run the makefile inside the work directory.
    subprocess.run(["make"], check=True, cwd=vhdlPath)

    for testFilePath in sorted(os.listdir(folderPath)):
        if not testFilePath.endswith('.c'):
            continue

        inputFilePath = os.path.join(folderPath, testFilePath)
        binaryFilePath = os.path.join(folderPath, f"{testFilePath}.bin")

        # Compile the binary file.
        cmd = [compilerPath, inputFilePath, "-o", binaryFilePath, "-m", "calci32"]
        if optimize:
            cmd += ["-O"]
        compileCFile = subprocess.run(cmd, capture_output=True)

        if compileCFile.returncode != 0:
            print(f"[\033[91mFAIL\033[0m] {testFilePath}: Failed to compile valid program.")
            if verboseLevel > 0:
                print(f"Output:\n{compileCFile.stderr.decode()}")
            
            results["failed"] += 1
            continue

        # Execute generated program.
        goodExecution = executeProgram(testFilePath, os.path.abspath(binaryFilePath), vhdlPath, verboseLevel > 0)
        if goodExecution:
            results["passed"] += 1
        else:
            results["failed"] += 1

    return results

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="fpga-tests")
    parser.add_argument("compiler", 
                        help="Path to the compiler executable")
    parser.add_argument("vhdl", 
                        help="Path to the VHDL project")
    parser.add_argument("tests", 
                        help="Path to the test folder. It can be a folder containing subfolders of tests")
    parser.add_argument("-v", "--verbose",
                        action="count", default=0,
                        help="Print output from the compiler.")
    parser.add_argument("-O", "--optimize",
                        action="store_true",
                        help="Run tests with optimizations.")

    args = parser.parse_args()
    
    if not os.path.exists(args.compiler):
        print(f"Error: Compiler not found at {args.compiler}")
        sys.exit(1)

    runTestsFromInputRoute(args.compiler, args.vhdl, args.tests, args.verbose, args.optimize)